<a href="https://colab.research.google.com/github/luissousa/study_book_DS/blob/main/data_science_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sudy of book Introducion to Data Science with PYTHON: Basics of Numpy and Pandas

## Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [3]:
L = list(range(11))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [5]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int, int]

Criando Arrays

In [6]:
np.zeros((3,5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.full((3,5),2.34)

array([[2.34, 2.34, 2.34, 2.34, 2.34],
       [2.34, 2.34, 2.34, 2.34, 2.34],
       [2.34, 2.34, 2.34, 2.34, 2.34]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.random.normal(0,1,(4,4))

array([[ 0.10125611,  0.06707662,  0.55381193, -1.29991643],
       [-0.20736603,  1.27204737,  0.17946687,  0.7083835 ],
       [-0.68047525, -1.32139016, -1.03292643, -0.9610472 ],
       [ 1.33490154,  1.81873699, -0.15289171,  1.17386594]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Indexing

In [11]:
x1 = np.array([9,8,7,4,9,4])

In [12]:
x1[0]

9

In [13]:
x1[4]

9

In [14]:
x1[-1]

4

In [15]:
x2 = np.array([[2,9,5,5],[5,1,6,9],[3,7,5,9]])
x2

array([[2, 9, 5, 5],
       [5, 1, 6, 9],
       [3, 7, 5, 9]])

In [16]:
x2[2,3]

9

In [17]:
x2[0,0]

2

Array Slicing

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:4]

array([0, 1, 2, 3])

In [20]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Array Concatenation

In [22]:
x = np.array([1,4,5])
y = np.array([3,7,9])
z = np.array([31,31,31])
np.concatenate([x,y,z])

array([ 1,  4,  5,  3,  7,  9, 31, 31, 31])

In [23]:
grid = np.array([[1,4,7],[3,5,9]])
np.concatenate([grid,grid])

array([[1, 4, 7],
       [3, 5, 9],
       [1, 4, 7],
       [3, 5, 9]])

In [24]:
x = np.array([2,4,7])
grid = np.array([[3,2,9],[17,18,19]])
np.vstack([x,grid])

array([[ 2,  4,  7],
       [ 3,  2,  9],
       [17, 18, 19]])

In [25]:
z = np.array([[8],[8]])
np.hstack([grid,z])


array([[ 3,  2,  9,  8],
       [17, 18, 19,  8]])

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


## Pandas

In [28]:
import pandas as pd
import numpy as np

### Data Frames

In [29]:
data = np.array([["",'Column1','Column2'],['Row1',10,20],['Row2',30,40]])

print(pd.DataFrame(data = data[1:,1:],index = data[1:,0],columns = data[0,1:]))

     Column1 Column2
Row1      10      20
Row2      30      40


In [30]:
data = pd.DataFrame({'Country':['Russia','Colombia','Chile','Equador','Ningeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4  Ningeria    11

In [31]:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


### Sorting Data

In [33]:
data = pd.DataFrame({'group':['x','x','x','y','y','y','z','z','z'],'ounces':[5,4,11,7,8.5,9,3,7,6]})
data

group  ounces
0     x     5.0
1     x     4.0
2     x    11.0
3     y     7.0
4     y     8.5
5     y     9.0
6     z     3.0
7     z     7.0
8     z     6.0

In [34]:
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
6     z     3.0
1     x     4.0
0     x     5.0
8     z     6.0
3     y     7.0
7     z     7.0
4     y     8.5
5     y     9.0
2     x    11.0

In [35]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     x    11.0
0     x     5.0
1     x     4.0
5     y     9.0
4     y     8.5
3     y     7.0
7     z     7.0
8     z     6.0
6     z     3.0

### Handling Outliers

In [36]:
data = pd.DataFrame({'x1':['one']*3 + ['two']*4,'x2':[3,2,1,3,3,4,4]})
data

x1  x2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [37]:
data.sort_values(by='x2')

x1  x2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [38]:
data.drop_duplicates()

x1  x2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [39]:
data.drop_duplicates(subset='x1')

x1  x2
0  one   3
3  two   3

In [40]:
data = pd.DataFrame({'food':['bacon','bacon','Pastrami','corned beef','pulled pork','Bacon','honey ham','pastrami','nova lox'],'ounces':[3,4,11,7,9.5,6,2,4,8]})
data

food  ounces
0        bacon     3.0
1        bacon     4.0
2     Pastrami    11.0
3  corned beef     7.0
4  pulled pork     9.5
5        Bacon     6.0
6    honey ham     2.0
7     pastrami     4.0
8     nova lox     8.0

In [41]:
food_to_animal = {'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

def food_2_animal(series):
  if series['food'] == 'bacon':
    return 'pig'
  elif series['food'] == 'pulled pork':
    return 'pig'
  elif series['food'] == 'pastrami':
    return 'cow'
  elif series['food'] == 'corned beef':
    return 'cow'
  elif series['food'] == 'honey ham':
    return 'pig'
  else:
    return 'salmon'
  
#creating new variable

data['animal'] = data['food'].map(str.lower).map(food_to_animal)
data

food  ounces  animal
0        bacon     3.0     pig
1        bacon     4.0     pig
2     Pastrami    11.0     cow
3  corned beef     7.0     cow
4  pulled pork     9.5     pig
5        Bacon     6.0     pig
6    honey ham     2.0     pig
7     pastrami     4.0     cow
8     nova lox     8.0  salmon

In [42]:
lower = lambda x: x.lower()

data['food'] = data['food'].apply(lower)

data['animal2'] = data.apply(food_2_animal, axis='columns')
data

food  ounces  animal animal2
0        bacon     3.0     pig     pig
1        bacon     4.0     pig     pig
2     pastrami    11.0     cow     cow
3  corned beef     7.0     cow     cow
4  pulled pork     9.5     pig     pig
5        bacon     6.0     pig     pig
6    honey ham     2.0     pig     pig
7     pastrami     4.0     cow     cow
8     nova lox     8.0  salmon  salmon

In [43]:
data.assign(newVariable = data['ounces']*5)

food  ounces  animal animal2  newVariable
0        bacon     3.0     pig     pig         15.0
1        bacon     4.0     pig     pig         20.0
2     pastrami    11.0     cow     cow         55.0
3  corned beef     7.0     cow     cow         35.0
4  pulled pork     9.5     pig     pig         47.5
5        bacon     6.0     pig     pig         30.0
6    honey ham     2.0     pig     pig         10.0
7     pastrami     4.0     cow     cow         20.0
8     nova lox     8.0  salmon  salmon         40.0

In [44]:
data.drop('animal2',axis='columns',inplace=True)
data

food  ounces  animal
0        bacon     3.0     pig
1        bacon     4.0     pig
2     pastrami    11.0     cow
3  corned beef     7.0     cow
4  pulled pork     9.5     pig
5        bacon     6.0     pig
6    honey ham     2.0     pig
7     pastrami     4.0     cow
8     nova lox     8.0  salmon

### Dealing witg Missing Values

In [45]:
data = np.array([3.,-799.,5.,-799.,-1000.,1.])
data

array([    3.,  -799.,     5.,  -799., -1000.,     1.])

In [46]:
data = np.where(data == -799, np.nan,data)
data

array([    3.,    nan,     5.,    nan, -1000.,     1.])

### Renaming Columns

In [47]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['USA','Canada','Russia'],columns=['a','b','c','d'])
data

a  b   c   d
USA     0  1   2   3
Canada  4  5   6   7
Russia  8  9  10  11

In [48]:
data.rename(index={'USA':'UK'},columns={'a':'new_a','b':'new_b'},inplace=True)
data

new_a  new_b   c   d
UK          0      1   2   3
Canada      4      5   6   7
Russia      8      9  10  11

In [49]:
data.rename(index = str.upper,columns=str.title,inplace=True)
data

New_A  New_B   C   D
UK          0      1   2   3
CANADA      4      5   6   7
RUSSIA      8      9  10  11

### Grouping Data

In [50]:
data = pd.DataFrame({'key1':['x','x','y','y','x'],'key2':['one','two','one','two','one'], 'data1' : np.random.randn(5), 'data2':np.random.randn(5)})
data

key1 key2     data1     data2
0    x  one  1.755822 -0.275682
1    x  two  0.869206 -0.038704
2    y  one  1.144604  0.371164
3    y  two -1.535250  0.126957
4    x  one -0.269546  2.175664

In [51]:
group = data['data1'].groupby(data['key1'])
#não entendi o funcionamento e o livro não mostra resultado
#só diz que houve um agrupamento

In [52]:
dates = pd.date_range('20180807',periods=6)
data = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
data

A         B         C         D
2018-08-07 -1.633262  0.918797  1.113828  0.824934
2018-08-08 -0.450372  1.867998 -1.372916  0.710637
2018-08-09  1.275093  1.180653  0.464323 -0.640329
2018-08-10  0.485291  1.297860  1.580976  0.633783
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457
2018-08-12 -0.559951 -0.147231  0.559986  0.438872

In [53]:
data[:3]

A         B         C         D
2018-08-07 -1.633262  0.918797  1.113828  0.824934
2018-08-08 -0.450372  1.867998 -1.372916  0.710637
2018-08-09  1.275093  1.180653  0.464323 -0.640329

In [54]:
data['20180807':'20180809']
#no livro estava errado, mas corrigi

A         B         C         D
2018-08-07 -1.633262  0.918797  1.113828  0.824934
2018-08-08 -0.450372  1.867998 -1.372916  0.710637
2018-08-09  1.275093  1.180653  0.464323 -0.640329

In [55]:
data.loc[:,['A','B']]

A         B
2018-08-07 -1.633262  0.918797
2018-08-08 -0.450372  1.867998
2018-08-09  1.275093  1.180653
2018-08-10  0.485291  1.297860
2018-08-11 -0.671672 -0.954904
2018-08-12 -0.559951 -0.147231

In [56]:
data.iloc[2:4,0:2]

A         B
2018-08-09  1.275093  1.180653
2018-08-10  0.485291  1.297860

In [57]:
dff = data.copy()
dff

A         B         C         D
2018-08-07 -1.633262  0.918797  1.113828  0.824934
2018-08-08 -0.450372  1.867998 -1.372916  0.710637
2018-08-09  1.275093  1.180653  0.464323 -0.640329
2018-08-10  0.485291  1.297860  1.580976  0.633783
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457
2018-08-12 -0.559951 -0.147231  0.559986  0.438872

In [58]:
data

A         B         C         D
2018-08-07 -1.633262  0.918797  1.113828  0.824934
2018-08-08 -0.450372  1.867998 -1.372916  0.710637
2018-08-09  1.275093  1.180653  0.464323 -0.640329
2018-08-10  0.485291  1.297860  1.580976  0.633783
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457
2018-08-12 -0.559951 -0.147231  0.559986  0.438872

In [59]:
data['E'] = ['one','two','two','three','four','five']
data

A         B         C         D      E
2018-08-07 -1.633262  0.918797  1.113828  0.824934    one
2018-08-08 -0.450372  1.867998 -1.372916  0.710637    two
2018-08-09  1.275093  1.180653  0.464323 -0.640329    two
2018-08-10  0.485291  1.297860  1.580976  0.633783  three
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457   four
2018-08-12 -0.559951 -0.147231  0.559986  0.438872   five

In [60]:
data[data['E'].isin(['two','five'])]

A         B         C         D     E
2018-08-08 -0.450372  1.867998 -1.372916  0.710637   two
2018-08-09  1.275093  1.180653  0.464323 -0.640329   two
2018-08-12 -0.559951 -0.147231  0.559986  0.438872  five

In [61]:
data[~data['E'].isin(['two','five'])]

A         B         C         D      E
2018-08-07 -1.633262  0.918797  1.113828  0.824934    one
2018-08-10  0.485291  1.297860  1.580976  0.633783  three
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457   four

In [62]:
data.query('B>C')

A         B         C         D     E
2018-08-08 -0.450372  1.867998 -1.372916  0.710637   two
2018-08-09  1.275093  1.180653  0.464323 -0.640329   two
2018-08-11 -0.671672 -0.954904 -1.199520 -0.783457  four

In [63]:
data.query('A<C|B>A')

A         B         C         D      E
2018-08-07 -1.633262  0.918797  1.113828  0.824934    one
2018-08-08 -0.450372  1.867998 -1.372916  0.710637    two
2018-08-10  0.485291  1.297860  1.580976  0.633783  three
2018-08-12 -0.559951 -0.147231  0.559986  0.438872   five

### Pivot Tables

In [64]:
data = pd.DataFrame({'group':['x','x','x','y','y','y','z','z','z'],'ounces':[3,4,10,8,9.1,8,4,7,9]})
data

group  ounces
0     x     3.0
1     x     4.0
2     x    10.0
3     y     8.0
4     y     9.1
5     y     8.0
6     z     4.0
7     z     7.0
8     z     9.0

In [65]:
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)

ounces
group          
x      5.666667
y      8.366667
z      6.666667

In [66]:
data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
x           3
y           3
z           3

### Exploring Large Datasets

lugar dos arquivos [arquivo](http://s3-ap-southeast-1.amazonaws.com/he-public-data/datafiles19cdaf8.zip)

Site: [Adult Dataset on UCI](https://archive.ics.uci.edu/ml/datasets/adult)

### In the dataset, *target* is the dependent variable. The dataset should be used in binary classification problems. Our goal is to be able to predict whether an individual has a salary of below or over 50K

In [67]:
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

In [68]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  31978 non-null  object
 14  target          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [69]:
print("The train dataset has {}".format(train.shape))
print("The test dataset has {}".format(test.shape))

The train dataset has (32561, 15)
The test dataset has (16281, 15)


In [70]:
train.head()

age          workclass  fnlwgt  ... hours.per.week  native.country  target
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [71]:
nans = train.shape[0] - train.dropna().shape[0]
print("{} rows in the train data have missing values".format(nans))

2399 rows in the train data have missing values


In [72]:
nand = test.shape[0] - test.dropna().shape[0]
print("{} rows in the test data have missing values".format(nand))

1221 rows in the test data have missing values


In [73]:
cat = train.select_dtypes(include=['O'])
cat.apply(pd.Series.nunique)

workclass          8
education         16
marital.status     7
occupation        14
relationship       6
race               5
sex                2
native.country    41
target             2
dtype: int64

In [77]:
train.workclass.value_counts(sort=True)
train.workclass.fillna('Private',inplace=True)

train.occupation.value_counts(sort=True)
train.occupation.fillna('Prof-speciality',inplace=True)

train['native.country'].value_counts(sort=True)
train['native.country'].fillna('United States',inplace=True)

train.isnull().sum()

train.target.value_counts()/train.shape[0]

 <=50K    0.75919
 >50K     0.24081
Name: target, dtype: float64

In [79]:
pd.crosstab(train.education, train.target, margins=True)/train.shape[0]

target            <=50K      >50K       All
education                                  
 10th          0.026750  0.001904  0.028654
 11th          0.034243  0.001843  0.036086
 12th          0.012285  0.001013  0.013298
 1st-4th       0.004975  0.000184  0.005160
 5th-6th       0.009736  0.000491  0.010227
 7th-8th       0.018611  0.001228  0.019840
 9th           0.014957  0.000829  0.015786
 Assoc-acdm    0.024631  0.008139  0.032769
 Assoc-voc     0.031357  0.011087  0.042443
 Bachelors     0.096250  0.068210  0.164461
 Doctorate     0.003286  0.009398  0.012684
 HS-grad       0.271060  0.051442  0.322502
 Masters       0.023464  0.029452  0.052916
 Preschool     0.001566  0.000000  0.001566
 Prof-school   0.004699  0.012991  0.017690
 Some-college  0.181321  0.042597  0.223918
All            0.759190  0.240810  1.000000

### Series